// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhkxnjrdfcwdbhvbhbwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhoa3huanJkZmN3ZGJodmJoYndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjAyODAsImV4cCI6MjA2MTY5NjI4MH0.fnrcsqnZBuReCl4fbxfxs2NbjD1VUqXJO5aImWzSokQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);